SELECT 
    SE_MARIER.NUMEROINSEE_MARI, SE_MARIER.NUMEROINSEE_FEMME, PERSONNE.NOM, PERSONNE.PRENOM
FROM PERSONNE INNER JOIN SE_MARIER ON (PERSONNE.NUMEROINSEE = SE_MARIER.NUMEROINSEE_FEMME) AND (PERSONNE.NUMEROINSEE = SE_MARIER.NUMEROINSEE_MARI);
